name: Publish to npm

changelog:
  sections:
    - title: ğŸš€ Features
      labels: ["feat"]
    - title: ğŸ› Fixes
      labels: ["fix"]
    - title: ğŸ§¹ Refactors
      labels: ["refactor"]
    - title: ğŸ“š Docs
      labels: ["docs"]
    - title: ğŸ§ª Tests
      labels: ["test"]
    - title: ğŸ”§ Build System
      labels: ["build"]
    - title: ğŸ›  Chores
      labels: ["chore"]

on:
  push:
    tags:
      - "v*.*.*"   # Run when pushing tags like v1.0.1

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # 1ï¸âƒ£ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2ï¸âƒ£ Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org/'

      # 3ï¸âƒ£ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4ï¸âƒ£ Build library
      - name: Build
        run: npm run build

      # 5ï¸âƒ£ Publish to npm
      - name: Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
