name: release-please

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      # 1ï¸âƒ£ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2ï¸âƒ£ Set up Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      # 3ï¸âƒ£ Run Release Please
      - name: Release Please
        uses: google-github-actions/release-please-action@v5
        with:
          release-type: node
          package-name: jalaali-ts
          changelog-path: CHANGELOG.md
          bump-minor-pre-major: true
          token: ${{ secrets.GITHUB_TOKEN }}
          changelog:
            categories:
              - title: ğŸ”§ Build System
                labels: ["build"]
              - title: ğŸ›  Chores
                labels: ["chore"]
              - title: âš¡ CI
                labels: ["ci"]
              - title: ğŸ“š Docs
                labels: ["docs"]
              - title: ğŸš€ Features
                labels: ["feat"]
              - title: ğŸ› Fixes
                labels: ["fix"]
              - title: ğŸ¯ Performance
                labels: ["perf"]
              - title: ğŸ§¹ Refactors
                labels: ["refactor"]
              - title: ğŸ¨ Styles
                labels: ["style"]
              - title: ğŸ§ª Tests
                labels: ["test"]
            exclude:
              labels: ["ignore-release", "skip-changelog"]
