name: Release Please

changelog:
  categories:
    - title: ğŸš€ Features
      labels: ["feat"]
    - title: ğŸ› Fixes
      labels: ["fix"]
    - title: ğŸ§¹ Refactors
      labels: ["refactor"]
    - title: ğŸ“š Docs
      labels: ["docs"]
    - title: ğŸ§ª Tests
      labels: ["test"]
    - title: ğŸ”§ Build System
      labels: ["build"]
    - title: ğŸ›  Chores
      labels: ["chore"]
  exclude:
    labels: ["ignore-release", "skip-changelog"]

on:
  push:
    branches: ["main"]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: jalaali-ts
